### ISSUE TITLE
60 FPS don't work

### ISSUE THREAD

**Issue by pontifex91** [Chip-Biscuit/hp-half-blood-prince-fix#1]
Hello! 60 FPS fix not working. I've successfully used your other fixes for Order of the Phoenix and Deathly Hallows Part 1/2 and 60 FPS works flawlessly there, however I can't seem to get 60 FPS for Half Blood Prince to work. 

I tried to use this fix on my PC Ryzen 3600\RTX 2060, as well as on the Steam Deck, and both have the same problem: the FPS counter shows that the game is running at 60 FPS, but in fact it remains running at 30 FPS. I also disabled Vsync via the NVIDIA control panel on PC, and via DXVK_CONFIG="d3d9.presentInterval = 0" on the Steam Deck, but this also does not help, the game continues to run at 30 FPS. 

When I use the hard solution with replacing 95BA0002 with 95BA0001 by editing the EXE file using a HEX editor, 60 FPS works perfectly, but when I use your fix, it doesn’t work.

**Comment by Chip-Biscuit** [comment]
hey,

thats interesting the fix does the edit you have done by using a hex editor, may i ask what version of half blood prince are you using? i think we may have had issues before on certain versions which havent worked with the fix. 

also did you put d3d9.dll and d3d9.ini and fps.dll all into the game path next to the exe?

are you able to edit fov and resolution and do window mode and the other features using this fix? 

if the fix is working it should uncap fps up to 280 fps 

we can try to go through it together and see if we can work out what the issues are here :)

**Comment by pontifex91** [comment]
Yes, I placed d3d9.dll, d3d9.ini and fps.dll in the game path next to the exe file. All other fixes work, I can enable your FPS counter (DisplayFPSCounter = 1) and it will show 60 FPS, also MSI Afterburner shows 60 FPS. When I disable Vsync, your meter shows 300 FPS, and MSI Afterburner shows 280. Field of view, windowed mode and other resolutions also work, everything is fine except for the actual 30 FPS.

**Comment by pontifex91** [comment]
I am using [this](https://rutor.info/torrent/553070/garri-potter-antologija_harry-potter-anthology-2001-2011-pc-repack-ot-r.g-catalyst) version (sorry for this link, but the game is difficult to find legally).

**Comment by Chip-Biscuit** [comment]
Do you have discord it would be easier for us to talk there in this server where we do all the fixing help stuff https://discord.gg/BkmKrsk8 the fix is most definitely working there for you but it would be easier for us to chat there in the technical help Chanel
